//prettier-ignore
const words = [
  "BASKETBALL", "FRIEND", "APPLE", "FLOWER", "ISLAND", "COOKIE", "GARDEN", "TRAVEL", "BEACH", "HORSE", "JUNGLE", "RAINBOW", "ADVENTURE", "SCIENCE", "SANDWICH", "MYSTERY", "VOLCANO", "FANTASY", "LIBRARY", "PIZZA", "SOCCER", "WHISPER", "UMBRELLA", "JOURNEY", "LEGEND", "ARTIST", "PAINTER", "CASTLE", "MAGIC", "DRAGON", "ROBOT", "PUZZLE", "GALAXY", "SAFARI", "BUTTERFLY", "STRAWBERRY", "WIZARD", "FESTIVAL", "ICEBERG", "TORNADO", "UNICORN", "CACTUS", "DINOSAUR", "FIREWORKS", "SKATEBOARD", "PANCAKE", "ELEPHANT", "DOLPHIN", "HAND", "ROAD", "LAMP", "DUCK", "WOLF", "KING", "BREAD", "ORANGE", "SHIRT", "INTERNET", "CHOCOLATE", "HAMBURGER", "WATERMELON", "ALLIGATOR", "ELEVATOR", "GIRAFFE", "SUPERHERO", "ELECTRICITY", "HELICOPTER", "MARATHON", "ENCYCLOPEDIA", "RELATIONSHIP", "POPULARITY", "COMMUNITY", "PHOTOGRAPHY", "CANDLE", "DOCTOR", "ROCKET", "CHICKEN", "MONSTER", "FOREST", "BAKERY", "CIRCUS", "COFFEE", "PIRATE", "OCEAN", "GUITAR", "PIANO", "LIZARD", "FAMILY", "IMAGINATION", "OCTOPUS", "TREASURE",
];

export const generateRandomWord = () => {
  const randomIndex = Math.floor(Math.random() * words.length);
  return words[randomIndex].split("");
};
